apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: r22de5w0q-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:ad86f30a0bdc82b10e7493003738fb7226485db8@sha256:35cd2c9a6c7c4f320ac884dd6c0ee4b24eefc9362e0cf4f29a026c47f651bb7a
          name: container-image
